site_name: Accreditation Standard
site_author: 'Chris Sharp'

theme: 
  name: material
  logo: 'images/logo.svg'
  palette:
    primary: 'indigo'
    accent: 'indigo'

nav:
    - Front: index.md
    - Background: standard/background.md
    - Rationale: standard/rationale.md
    - Badges: standard/badges.md
    - The Process: standard/process.md
    - The Standard: standard/standard.md
    - Appendices:
        Publications:
          - Accreditation Strategy: pubs/IoC-AP-10-1.pdf
          - Analysis of Accreditation Approaches: pubs/IoC-D1-1-1.pdf
          - Comparison of Accreditation Approaches: pubs/IoC-AP-13-1-V2.pdf
          - Mapping Portfolio Evidence to SFIA: pubs/IoC-AP-12-2-V2.pdf
          - Statements of Alignment: pubs/IoC-D1-1-5.pdf
          - Submission Template: pubs/IoC-ST-1-0.pdf
          - Portfolio Mapping Example: pubs/IoC-PM-1-0.pdf
          - Demonstrating SFIA Generic Responsibility Characteristics: pubs/IoC-RC.pdf
        Designing a Curriculum: appendices/design.md
        Generic Skills: appendices/generic.md
        Data Analytics: appendices/data-analytics.md
        Cybersecurity: appendices/cybersecurity.md
        Web Developer: 
          - Curriculum: appendices/web-dev.md
          - Modules:
            - ARCH202: appendices/courses/ARCH202.md
            - BSYS101: appendices/courses/BSYS101.md
            - CLIN102: appendices/courses/CLIN102.md
            - CLIN202: appendices/courses/CLIN202.md
            - COMP102: appendices/courses/COMP102.md
            - CSVC301: appendices/courses/CSVC301.md
            - DMAD201: appendices/courses/DMAD201.md
            - INTN: appendices/courses/INTN.md
            - LEAN302: appendices/courses/LEAN302.md
            - MOBS302: appendices/courses/MOBS302.md
            - NWSC101: appendices/courses/NWSC101.md
            - NWSC202: appendices/courses/NWSC202.md
            - PROF102: appendices/courses/PROF102.md
            - PROG101: appendices/courses/PROG101.md
            - PROJ201: appendices/courses/PROJ201.md
            - PROJ301: appendices/courses/PROJ301.md
            - PROJ302: appendices/courses/PROJ302.md
            - RQMS301: appendices/courses/RQMS301.md
            - SPMG201: appendices/courses/SPMG201.md
            - SYSI301: appendices/courses/SYSI301.md
            - UCDD201: appendices/courses/UCDD201.md
            - WEBD102: appendices/courses/WEBD102.md
            - WEBP202: appendices/courses/WEBP202.md
        SFIA Skills: 
          - Overview: appendices/skills/index.md
          - Leadership: appendices/skills/leadership.md
          - Experience: appendices/skills/work-experience.md
          - ARCH: appendices/skills/arch.md
          - DTAN: appendices/skills/dtan.md
          - HCEV: appendices/skills/hcev.md
          - INCA: appendices/skills/inca.md
          - PROF: appendices/skills/prof.md
          - PROG: appendices/skills/prog.md
          - RELM: appendices/skills/relm.md
          - REQM: appendices/skills/reqm.md
          - SCTY: appendices/skills/scty.md
          - SINT: appendices/skills/sint.md

plugins:
    - search
    - markdownextradata
    - pdf-export:
        verbose: false
        combined: false
        media_type: print
        enabled_if_env: ENABLE_PDF_EXPORT

markdown_extensions:
  - footnotes
  - markdown_blockdiag:
      format: svg

extra:
  spec:
    version: 1.0

extra_css:
  - 'stylesheets/extra.css'
